export const todos = [
  {
    id: 1,
    title:
      "delectus aut autemutemdelectus aut autemdelectus aut autem delectus aut autemdelectus aut autemdelectus aut autem delectus aut autemdelectus aut autemdelectus aut autem",
    content:
      "delectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autemdelectus aut autem",
    status: "pending",
    category: "normal",
    date: "2021-09-01",
  },
  {
    id: 2,
    title: "quis ut nam facilis et officia qui qui uis ut nam facilis et officia qu",
    content: "quis ut nam facilis et officia qui uis ut nam facilis et officia qui",
    status: "done",
    category: "primary",
    date: "2021-09-01",
  },
  {
    id: 3,
    title: "fugiat veniam minus",
    content: "fugiat veniam minus",
    status: "doing",
    category: "normal",
    date: "2021-09-01",
  },
  {
    id: 4,
    title: "delectus aut autem",
    content: "delectus aut autem",
    status: "doing",
    category: "primary",
    date: "2021-09-01",
  },
  {
    id: 5,
    title: "quis ut nam facilis et officia qui",
    content: "quis ut nam facilis et officia qui quis ut nam facilis et officia qui",
    status: "pending",
    category: "primary",
    date: "2021-09-01",
  },
  {
    id: 6,
    title: "fugiat veniam minus",
    content: "fugiat veniam minus",
    status: "done",
    category: "normal",
    date: "2021-09-01",
  },
  {
    id: 7,
    title: "delectus aut autem",
    content: "delectus aut autem",
    status: "pending",
    category: "normal",
    date: "2021-09-01",
  },
  {
    id: 8,
    title: "quis ut nam facilis et officia qui",
    content: "quis ut nam facilis et officia qui",
    status: "done",
    category: "primary",
    date: "2021-09-01",
  },
  {
    id: 9,
    title: "fugiat veniam minus",
    content: "fugiat veniam minus",
    status: "doing",
    category: "normal",
    date: "2021-09-01",
  },
];
